spring.application.name=oraklast

# Firebase credentials path
#firebase.credentials.path=C:/java-apis/firebase_notify_api/fcm-flood-monitoring-5a45f1d43d7b.json
firebase.credentials.path=/home/kauesanchesg/development/java/firebase_notify_api/fcm-flood-monitoring-5a45f1d43d7b.json