spring.application.name=oraklast
server.port=${PORT:8080}

# Firebase credentials path
#firebase.credentials.path=C:/java-apis/firebase_notify_api/fcm-flood-monitoring-5a45f1d43d7b.json
#firebase.credentials.pJath=/home/kauesanchesg/development/java/firebase_notify_api/fcm-flood-monitoring-5a45f1d43d7b.json
